# This workflow will upload a Python Package to PyPI when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: LiveApex

on:
  push:
    branches:
    - dev

permissions:
  contents: read

jobs:
  release-build:
    runs-on: linux-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Build release distributions
        run: >-
          python3 -m
          pip install
          build
          --user

      - name: Build Python 3
        run: python3 -m build

      - name: Store packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish-to-pypi:
    name: >-
      Publish LiveApex to PyPI
    needs:
    - release-build
    runs-on: windows-latest
    environment:
      name: pypi
      url: https://pypi.org/p/liveapex
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: pypi-publish
        uses: pypa/gh-action-pypi-publish@v1.12.3
            
