# This workflow will upload a Python Package to PyPI when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: LiveApex

on:
  push:
    branches:
    - dev

permissions:
  contents: read
  id-token: write

jobs:
  check-commit-message:
    name: Check commit message
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check commit message for version tag
        id: check_version
        run: |
          if [[ "$(git log -1 --pretty=%B)" =~ \[[0-9]+\.[0-9]+\.[0-9]+(-[A-Za-z0-9]+)?\] ]]; then
            echo "Version tag found in commit message."
            echo "check_passed=true" >> $GITHUB_ENV
            echo "::set-output name=check_passed::true"
          else
            echo "No version tag found in commit message. Skipping publish."
            echo "check_passed=false" >> $GITHUB_ENV
            echo "::set-output name=check_passed::false"
          fi

    outputs:
      check_passed: ${{ steps.check_version.outputs.check_passed }}

  release-build:
    name: Build Release
    needs: check-commit-message
    if: ${{ needs.check-commit-message.outputs.check_passed == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Build release distributions
        run: |
          python3 -m pip install build --user
          python3 -m build

      - name: Store packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish-to-pypi:
    name: Publish to PyPI
    needs: release-build
    if: ${{ needs.check-commit-message.outputs.check_passed == 'true' }}
    runs-on: ubuntu-latest
    environment:
      name: test-pypi
      url: https://test.pypi.org/legacy/
    permissions:
      id-token: write

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.3
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true
          # user: __token__
          # password: ${{ secrets.TEST_PYPI_API_TOKEN }}